## *1. Perform a set of exercises*
* *Excercise 2. Enter the number n. Arrange 1 and 0 in a checkerboard pattern starting with 0 in a matrix of size nхn, using slicing.*

In [5]:
import numpy as np
n =int(input(" enter the number :"))
arr = np.zeros((n, n), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

 enter the number :5
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


* *Excercise 5. Enter the number n. Output an array of size nхn, in which the rows with the even indices are equal to 1, and in others are equal to 0.*

In [6]:
import numpy as np
n =int(input(" enter"))
arr = np.zeros((n, n), dtype=int)
arr[::2, ::] = 1
print(arr)

 enter5
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


* *Excercise 11. Create an array of 1 of size nхn and add to it a "border" formed from 0*

In [7]:
import numpy as np
n =int(input(" enter"))
arr = np.ones((n+2, n+2), dtype=int)
arr[0] = 0
arr[-1] = 0
arr[:, 0] = 0
arr[:, -1] = 0
print(arr)
arr[0]=0

 enter4
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


* *Excercise 12. Create an array of 1 of size nхn and create an inside "border" formed from 0.*

In [8]:
import numpy as np
n =int(input(" enter"))
arr = np.ones((n, n), dtype=int)
arr[0] = 0
arr[-1] = 0
arr[:, 0] = 0
arr[:, -1] = 0
print(arr)
arr[0]=0

 enter4
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


* Excercise 13. Determine the index of 70-th element in a vector, if it is converted into a matrix of size 4x5x6.

In [9]:
n = 4
m = 5
k = 6
h = 69
x = (h // (m * k), (h % (m * k)) // k, (h % (m * k)) % k)

print('In the matrix of {}х{}х{} index {} element {}'.format(n, m, k, h + 1, str(x)))

In the matrix of 4х5х6 index 70 element (2, 1, 3)


* Excercise 14. Arrange 1 and 0 on the 8х8 field in a checkerboard pattern using the repeat function (*).

In [4]:
import numpy as np
arr = np.array([[0,1,0,1,0,1,0,1],
               [1,0,1,0,1,0,1,0]]*4)
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


* Excercise 16. Fill the even columns of the matrix of nхn size with 1, and the odd ones with 0.

In [10]:
import numpy as np
n = int(input())
arr = np.zeros((n,n), dtype=int)
arr[::,1::2]=1
print(arr)

5
[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]


* Excercise 17. Fill the vector with values from 0 to n. Replace all values greater than n/2 and less than 3n/4 with zeros.

In [11]:
import numpy as np

n = int(input("Enter a number : "))
x = np.arange(n+1)
l, r = np.split(x, [n//4+1])
r[r < 3*n/4] = 0
print(x)


Enter a number : 10
[ 0  1  2  0  0  0  0  0  8  9 10]


* Excercise 20. Generate a vector of n elements that are evenly spaced on the interval (0,1) i.e. both ends of the interval are not included. Output values up to 3 decimal places.

In [12]:
import numpy as np
n = int(input("Enter a number :  "))
np.around(np.linspace(0, 1, n+2, dtype=float),3)[1:-1:]

Enter a number :  10


array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818,
       0.909])

## 2. Solve the system of linear equations using Cramer's formulas and perform a test using:
#### a) matrix multiplication;
#### b) numpy.linalg.solve().

In [13]:
import numpy as np

coef_matrix = np.array([[1,2,3,-2],
                       [1,-1,-2,-3],
                       [3,2,-1,2],
                       [2,-3,2,1]])
det = np.linalg.det(coef_matrix)
b_matrix= np.array([6,8,4,-8])
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:, 0] =  b_matrix
det_1 = np.linalg.det(coef_matrix_1)
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:,1] = b_matrix
det_2 = np.linalg.det(coef_matrix_1)
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:,2] = b_matrix
det_3 = np.linalg.det(coef_matrix_1)
coef_matrix_1 = coef_matrix.copy()
coef_matrix_1[:,3] = b_matrix
det_4 = np.linalg.det(coef_matrix_1)
x_matrix = np.array([round(det_1/det),round(det_2/det),round(det_3/det),round(det_4/det)])
print(coef_matrix.dot(x_matrix))
print(np.linalg.solve(coef_matrix, b_matrix))
print("X array: ",x_matrix)

[ 6.  7.  4. -8.]
[ 1.125   1.9375 -1.125  -2.1875]
X array:  [ 1.  2. -1. -2.]


 ## 3. Calculate the value of the matrix expression.

In [14]:
import numpy as np

A = np.array([[4,5,-2],[3,-1,0],[4,2,7]], dtype=int)
B = np.array([[2,1,-1],[0,1,3],[5,7,3]], dtype=int)

print(2*A-(A-2*B)*B)

[[ 8  7 -4]
 [ 6  1 18]
 [38 88 11]]


## 4. Solve the matrix equation using an inverse matrix and perform a test using:
#### a) matrix multiplication;
#### b) numpy.linalg.solve().

In [15]:
import numpy as np
a = np.array([[2, 3, 1],
              [-1, 2, 4],
              [5, 3, 0]])
b = np.array([[2, 7, 13],
              [-1, 0, 5],
              [5, 13, 21]])
x = np.linalg.inv(a)@ b
print(x)


[[ 1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
